Read dataset

In [2]:
import pandas as pd 

df = pd.read_csv('cafe_scrap.csv')

df

,input_id,link,title,category,address,open_hours,popular_times,website,phone,plus_code,...,reservations,order_online,menu,owner,complete_address,credit_cards_accepted,about,user_reviews,user_reviews_extended,emails
0,3043499d-f7a0-4139-b121-07920cff8870,https://www.google.com/maps/place/Kise+Coffee/...,Kise Coffee,Coffee shop,"Melayu (Di Arena Suzuki Bagian Kiri, Jl. A. Ya...","{""Friday"":[""9.00 am–12.00 am""],""Monday"":[""9.00...","{""Friday"":{""10"":68,""11"":81,""12"":84,""13"":75,""14...",NaN,NaN,"MJG3+69 Melayu, Banjarmasin City, South Kalima...",...,NaN,NaN,"{""link"":"""",""source"":""""}","{""id"":""113214016193856501526"",""name"":""Kise Cof...","{""borough"":""Melayu, Banjarmasin Tengah"",""stree...",NaN,"[{""id"":""service_options"",""name"":""Service optio...","[{""Name"":""fa tamb"",""ProfilePicture"":""https://l...",NaN,NaN
1,3043499d-f7a0-4139-b121-07920cff8870,https://www.google.com/maps/place/Berdua+Coffe...,Berdua Coffee,Coffee shop,"Jl. A. Yani No.147, Karang Mekar, Kec. Banjarm...","{""Friday"":[""7.30 pm–2.00 am""],""Monday"":[""7.30 ...",{},NaN,NaN,"MJC5+R4 Karang Mekar, Banjarmasin City, South ...",...,NaN,NaN,"{""link"":"""",""source"":""""}","{""id"":"""",""name"":""Berdua Coffee (Owner)"",""link""...","{""borough"":""Karang Mekar, Banjarmasin Timur"",""...",NaN,"[{""id"":""offerings"",""name"":""Offerings"",""options...","[{""Name"":""Zainur Rahmani"",""ProfilePicture"":""ht...",NaN,NaN
2,3043499d-f7a0-4139-b121-07920cff8870,https://www.google.com/maps/place/Caffeinated/...,Caffeinated,Coffee shop,"Jl. Manggis No.19a, RT.17/RW.02, Kuripan, Kec....","{""Friday"":[""3.00 pm–1.00 am""],""Monday"":[""3.00 ...",{},NaN,0878-1224-8425,"MJH6+24 Kuripan, Banjarmasin City, South Kalim...",...,NaN,NaN,"{""link"":"""",""source"":""""}","{""id"":"""",""name"":""Caffeinated (Owner)"",""link"":""""}","{""borough"":""Kuripan, Banjarmasin Timur"",""stree...",NaN,"[{""id"":""service_options"",""name"":""Service optio...","[{""Name"":""Siti Nurana"",""ProfilePicture"":""https...",NaN,NaN
3,3043499d-f7a0-4139-b121-07920cff8870,https://www.google.com/maps/place/DE+VILLAGE+C...,DE VILLAGE CAFE,Cafe,"diatas Toko Tifa Home decor Bjm, Jl. Manggis N...","{""Friday"":[""11.00 am–11.00 pm""],""Monday"":[""11....","{""Friday"":{""10"":0,""11"":33,""12"":37,""13"":40,""14""...",NaN,0882-0098-80112,"MJH6+G2 Kuripan, Banjarmasin City, South Kalim...",...,NaN,NaN,"{""link"":"""",""source"":""""}","{""id"":""112624305392656267049"",""name"":""DE VILLA...","{""borough"":""Kuripan, Banjarmasin Timur"",""stree...",NaN,"[{""id"":""service_options"",""name"":""Service optio...","[{""Name"":""aisha saputri"",""ProfilePicture"":""htt...",NaN,NaN
4,3043499d-f7a0-4139-b121-07920cff8870,https://www.google.com/maps/place/All-Co+Veter...,All-Co Veteran,Coffee shop,"Sebrang Pertigaan, Jl. Veteran Jl. Manggis, Su...","{""Friday"":[""9.00 am–11.00 pm""],""Monday"":[""9.00...",{},https://www.instagram.com/all.co_veteran?igsh=...,0895-7051-24859,"MJJ5+2W Sungai Bilu, Banjarmasin City, South K...",...,NaN,NaN,"{""link"":"""",""source"":""""}","{""id"":""104020627041038474485"",""name"":""All-Co V...","{""borough"":""Sungai Bilu, Banjarmasin Timur"",""s...",NaN,"[{""id"":""service_options"",""name"":""Service optio...","[{""Name"":""fadel"",""ProfilePicture"":""https://lh3...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247,7b7b74fe-1364-4bd8-94a8-bf8df1501912,https://www.google.com/maps/place/SERENITY+COF...,SERENITY COFFEE,Coffee shop,"MHGR+PW9 SERENITY COFFEE, Kertak Baru Ulu, Ban...","{""Friday"":[""9.00 am–11.00 pm""],""Monday"":[""9.00...","{""Friday"":{""10"":90,""11"":94,""12"":94,""13"":100,""1...",NaN,NaN,NaN,...,NaN,NaN,"{""link"":"""",""source"":""""}","{""id"":"""",""name"":""SERENITY COFFEE (Owner)"",""lin...","{""borough"":""Kertak Baru Ulu, Banjarmasin Tenga...",NaN,"[{""id"":""service_options"",""name"":""Service optio...","[{""Name"":""Muhammad Wais Al Kurni (Wais)"",""Prof...",NaN,NaN
1248,7b7b74fe-1364-4bd8-94a8-bf8df1501912,https://www.google.com/maps/place/Alenia+Coffe...,Alenia Coffee & Eatery,Coffee shop,"Jl. S. Parman No.89, Belitung Utara, Kec. Banj...","{""Friday"":[""5.00 pm–12.00 am""],""Monday"":[""5.00...","{""Friday"":{""10"":0,""11"":0,""12"":0,""13"":0,""14"":0,...",NaN,NaN,"MHRQ+6F Belitung Utara, Banjarmasin City, Sout...",...,NaN,NaN,"{""link"":"""",""source"":""""}","{""id"":"""",""name"":""Alenia Coffee \u0026 Eatery (...","{""borough"":""Belitung Utara, Banjarmasin Barat""...",NaN,"[{""id"":""service_options"",""name"":""Service optio...","[{""Name"":""Bubblebee_Ayy"",""ProfilePicture"":""htt...",NaN,NaN
1249,7b7b74fe-1364-4bd8-94a8-bf8df1501912,https://www.google.com/maps/place/TUSUK+KOFFEE...,TUSUK KOFFEE,Coffee shop,"Jl. Bank Rakyat No.33, Kertak Baru Ulu, Banjar...","{""Friday"":[""7.00 am–1.00 am""],""Monday"":[""7.00 ...","{""Friday"":{""0"":30,""10"":21,""11"":22,""12"":22,""13""...",NaN,0881-1141-970,"MHGR+HX Kertak Baru Ulu, Banjarmasin City, Sou...",...,NaN,NaN,"{""link"":"""",""source"":""""}","{""id"":""106202336653967277012"",""name"":""TUSUK KO...","{""borough"":""Kertak Baru Ulu, Banjarmasin Tenga...",NaN,"[{""id"":""service_options"",""name"":""Service optio...","[{""Name"":""Yutika Adnindya"",""ProfilePicture"":""h...",NaN,NaN
1250,7b7b74fe-1364-4bd8-94a8-bf8df1501912,https://www.google.com/maps/place/Aiakawa+Coff...,Aiakawa Coffee Kawan 4,Coffee shop,Jl. Brigjen H Jl. Brigjend H. Hasan Basri No.0...,"{""Friday"":[""8.00 am–11.30 pm""],""Monday"":[""8.00...","{""Friday"":{""10"":26,""11"":20,""12"":18,""13"":18,""14...",https://aiakawa-coffee-kawan-4-coffee-shop-ban...,0821-8975-2190,"MHXQ+8P Sungai Miai, Banjarmasin City, South K...",...,NaN,NaN,"{""link"":""/url?q=https://gofood.co.id/en/banjar...","{""id"":""104274695479347077541"",""name"":""Aiakawa ...","{""borough"":""Sungai Miai, Banjarmasin Utara"",""s...",NaN,"[{""id"":""service_options"",""name"":""Service optio...","[{""Name"":""narnia forger"",""ProfilePicture"":""htt...",NaN,NaN
1251,7b7b74fe-1364-4bd8-94a8-bf8df1501912,https://www.google.com/maps/place/Enchante+Bis...,Enchante Bistro & Cafe,Cafe,"Jl. M.T. Haryono, Kertak Baru Ilir, Banjarmasi...","{""Friday"":[""10.00 am–10.30 pm""],""Monday"":[""10....","{""Friday"":{""10"":21,""11"":21,""12"":32,""13"":50,""14...",https://www.instagram.com/enchantebistrocafe,0851-8330-9168,"MHFQ+M7 Kertak Baru Ilir, Banjarmasin City, So...",...,NaN,NaN,"{""link"":"""",""source"":""""}","{""id"":""115161001216101014967"",""name"":""Enchante...","{""borough"":""Kertak Baru Ilir, Banjarmasin Teng...",NaN,"[{""id"":""service_options"",""name"":""Service optio...","[{""Name"":""Nia Rahma"",""ProfilePicture"":""https:/...",NaN,NaN

In [3]:
pd.set_option('display.max_info_columns', 50)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1252 entries, 0 to 1251
Data columns (total 36 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   input_id               1252 non-null   str
 1   link                   1252 non-null   str
 2   title                  1252 non-null   str
 3   category               1250 non-null   str
 4   address                1252 non-null   str
 5   open_hours             1252 non-null   str
 6   popular_times          1252 non-null   str
 7   website                228 non-null    str
 8   phone                  705 non-null    str
 9   plus_code              736 non-null    str
 10  review_count           1252 non-null   int64
 11  review_rating          1252 non-null   float64
 12  reviews_per_rating     1252 non-null   str
 13  latitude               1252 non-null   float64
 14  longitude              1252 non-null   float64
 15  cid                    1252 non-null   uint64
 16  status                 148 non-null    str
 17  descriptions           7 non-null      str
 18  reviews_link           0 non-null      float64
 19  thumbnail              1240 non-null   str
 20  timezone               1252 non-null   str
 21  price_range            674 non-null    str
 22  data_id                1252 non-null   str
 23  street_view_url        1134 non-null   str
 24  place_id               1252 non-null   str
 25  images                 1252 non-null   str
 26  reservations           11 non-null     str
 27  order_online           11 non-null     str
 28  menu                   1252 non-null   str
 29  owner                  1252 non-null   str
 30  complete_address       1252 non-null   str
 31  credit_cards_accepted  90 non-null     str
 32  about                  1245 non-null   str
 33  user_reviews           1252 non-null   str
 34  user_reviews_extended  0 non-null      float64
 35  emails                 0 non-null      float64
dtypes: float64(6), int64(1), str(28), uint64(1)
memory usage: 352.3 KB

In [4]:
for i, col in enumerate(df.columns):
    print(f"{i}: {col}")

0: input_id
1: link
2: title
3: category
4: address
5: open_hours
6: popular_times
7: website
8: phone
9: plus_code
10: review_count
11: review_rating
12: reviews_per_rating
13: latitude
14: longitude
15: cid
16: status
17: descriptions
18: reviews_link
19: thumbnail
20: timezone
21: price_range
22: data_id
23: street_view_url
24: place_id
25: images
26: reservations
27: order_online
28: menu
29: owner
30: complete_address
31: credit_cards_accepted
32: about
33: user_reviews
34: user_reviews_extended
35: emails

In [ ]:
df = df.drop(columns=['reviews_link', 'user_reviews_extended', 'emails', 'user_reviews', 'thumbnail', 'street_view_url'])

for i, col in enumerate(df.columns):
    print(f"{i}: {col}")

0: input_id
1: link
2: title
3: category
4: address
5: open_hours
6: popular_times
7: website
8: phone
9: plus_code
10: review_count
11: review_rating
12: reviews_per_rating
13: latitude
14: longitude
15: cid
16: status
17: descriptions
18: timezone
19: price_range
20: data_id
21: place_id
22: images
23: reservations
24: order_online
25: menu
26: owner
27: complete_address
28: credit_cards_accepted
29: about

In [7]:
df = df.drop_duplicates()

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1252 entries, 0 to 1251
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   input_id               1252 non-null   str
 1   link                   1252 non-null   str
 2   title                  1252 non-null   str
 3   category               1250 non-null   str
 4   address                1252 non-null   str
 5   open_hours             1252 non-null   str
 6   popular_times          1252 non-null   str
 7   website                228 non-null    str
 8   phone                  705 non-null    str
 9   plus_code              736 non-null    str
 10  review_count           1252 non-null   int64
 11  review_rating          1252 non-null   float64
 12  reviews_per_rating     1252 non-null   str
 13  latitude               1252 non-null   float64
 14  longitude              1252 non-null   float64
 15  cid                    1252 non-null   uint64
 16  status                 148 non-null    str
 17  descriptions           7 non-null      str
 18  timezone               1252 non-null   str
 19  price_range            674 non-null    str
 20  data_id                1252 non-null   str
 21  place_id               1252 non-null   str
 22  images                 1252 non-null   str
 23  reservations           11 non-null     str
 24  order_online           11 non-null     str
 25  menu                   1252 non-null   str
 26  owner                  1252 non-null   str
 27  complete_address       1252 non-null   str
 28  credit_cards_accepted  90 non-null     str
 29  about                  1245 non-null   str
dtypes: float64(3), int64(1), str(25), uint64(1)
memory usage: 293.6 KB

In [ ]:
df = df.drop(columns=['descriptions', 'status', 'price_range', 'credit_cards_accepted', 'about'])

df.info()

KeyError: "['descriptions', 'status', 'price_range', 'credit_cards_accepted', 'about'] not found in axis"

In [10]:


df = df.drop(columns=['phone', 'plus_code', 'website'])

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1252 entries, 0 to 1251
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   input_id            1252 non-null   str
 1   link                1252 non-null   str
 2   title               1252 non-null   str
 3   category            1250 non-null   str
 4   address             1252 non-null   str
 5   open_hours          1252 non-null   str
 6   popular_times       1252 non-null   str
 7   review_count        1252 non-null   int64
 8   review_rating       1252 non-null   float64
 9   reviews_per_rating  1252 non-null   str
 10  latitude            1252 non-null   float64
 11  longitude           1252 non-null   float64
 12  cid                 1252 non-null   uint64
 13  timezone            1252 non-null   str
 14  data_id             1252 non-null   str
 15  place_id            1252 non-null   str
 16  images              1252 non-null   str
 17  reservations        11 non-null     str
 18  order_online        11 non-null     str
 19  menu                1252 non-null   str
 20  owner               1252 non-null   str
 21  complete_address    1252 non-null   str
dtypes: float64(3), int64(1), str(17), uint64(1)
memory usage: 215.3 KB

In [12]:
df = df.drop(columns=['timezone', 'reservations', 'order_online', 'complete_address', 'owner', 'order_online'])

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1252 entries, 0 to 1251
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   input_id            1252 non-null   str
 1   link                1252 non-null   str
 2   title               1252 non-null   str
 3   category            1250 non-null   str
 4   address             1252 non-null   str
 5   open_hours          1252 non-null   str
 6   popular_times       1252 non-null   str
 7   review_count        1252 non-null   int64
 8   review_rating       1252 non-null   float64
 9   reviews_per_rating  1252 non-null   str
 10  latitude            1252 non-null   float64
 11  longitude           1252 non-null   float64
 12  cid                 1252 non-null   uint64
 13  data_id             1252 non-null   str
 14  place_id            1252 non-null   str
 15  images              1252 non-null   str
 16  menu                1252 non-null   str
dtypes: float64(3), int64(1), str(12), uint64(1)
memory usage: 166.4 KB

In [15]:
df = df.dropna(subset=['category'])

df = df.drop_duplicates(subset=['place_id'])

df = df.drop_duplicates(subset=['cid'])

df = df.drop_duplicates(subset=['data_id'])

df.info()

<class 'pandas.DataFrame'>
Index: 1250 entries, 0 to 1251
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   input_id            1250 non-null   str
 1   link                1250 non-null   str
 2   title               1250 non-null   str
 3   category            1250 non-null   str
 4   address             1250 non-null   str
 5   open_hours          1250 non-null   str
 6   popular_times       1250 non-null   str
 7   review_count        1250 non-null   int64
 8   review_rating       1250 non-null   float64
 9   reviews_per_rating  1250 non-null   str
 10  latitude            1250 non-null   float64
 11  longitude           1250 non-null   float64
 12  cid                 1250 non-null   uint64
 13  data_id             1250 non-null   str
 14  place_id            1250 non-null   str
 15  images              1250 non-null   str
 16  menu                1250 non-null   str
dtypes: float64(3), int64(1), str(12), uint64(1)
memory usage: 175.8 KB

In [17]:
print(df['category'].unique())

<StringArray>
[                 'Coffee shop',                         'Cafe',
                   'Juice shop',                   'Donut shop',
                    'Cake shop',               'Ice cream shop',
 'Food and beverage consultant',                   'Restaurant',
                 'Espresso bar',                 'Coffee store',
                       'Bakery',                 'Coffee stand',
              'Coffee roastery',                     'Art cafe',
                          'Bar',                 'Dessert shop',
                   'Night club',            'Buffet restaurant',
            'Seblak restaurant',                 'Soup kitchen',
           'Chicken restaurant',                'Internet cafe',
            'Brunch restaurant',                    'Rest stop',
                     'Car wash',                        'Diner',
                    'Snack bar',                'General store',
              'Children's cafe',                        'Lodge',
         'Fast food restaurant',        'Indonesian restaurant',
            'Health consultant',         'Hamburger restaurant',
              'Nasi restaurant',           'Seafood restaurant',
             'Bakso restaurant',         'Traditional teahouse',
                    'Brasserie',      'Coffee machine supplier',
            'Convenience store',               'Chocolate cafe',
                  'Noodle shop',                    'Pool hall',
                  'Karaoke bar',                  'Steak house',
          'Barbecue restaurant',             'Asian restaurant',
                       'Garden',           'Chinese restaurant',
          'Japanese restaurant',               'Clothing store',
             'Pizza restaurant',         'Breakfast restaurant']
Length: 54, dtype: str

In [18]:
df[df['category'] == 'Night club']

,input_id,link,title,category,address,open_hours,popular_times,review_count,review_rating,reviews_per_rating,latitude,longitude,cid,data_id,place_id,images,menu
467,e399366b-ca17-4837-aaa6-8384ff2b8ed1,https://www.google.com/maps/place/Cafe+ternak/...,Cafe ternak,Night club,"JFCF+847 Cafe ternak, Mampari, Kec. Batu Mandi...","{""Friday"":[""Open 24 hours""],""Monday"":[""Open 24...","{""Friday"":{""0"":24,""1"":24,""10"":28,""11"":28,""12"":...",2,5.0,"{""1"":0,""2"":0,""3"":0,""4"":0,""5"":2}",-2.379121,115.472785,1306311030620759254,0x2de545002a17d125:0x1220f2f6125324d6,ChIJJdEXKgBF5S0R1iRTEvbyIBI,"[{""title"":""All"",""image"":""https://lh3.googleuse...","{""link"":"""",""source"":""""}"
1001,b6820552-2113-494b-9a3c-621f13137e91,https://www.google.com/maps/place/Cafe+99+Kara...,Cafe 99 Karaoke,Night club,"RCFF+7H7 Cafe 99 Karaoke, Jl. Mabuun Raya, Mab...",{},{},3,4.7,"{""1"":0,""2"":0,""3"":0,""4"":1,""5"":2}",-2.176842,115.423931,3640142377518367736,0x2dfab37d3e5ac99f:0x32846234bfd403f8,ChIJn8laPn2z-i0R-APUvzRihDI,"[{""title"":""All"",""image"":""https://streetviewpix...","{""link"":"""",""source"":""""}"
1008,b6820552-2113-494b-9a3c-621f13137e91,https://www.google.com/maps/place/cafe+angel/d...,cafe angel,Night club,"VF83+93G cafe angel, Dekat, Jl. Tj. - Kuaro, K...","{""Friday"":[""7.00 pm–4.30 am""],""Monday"":[""7.00 ...","{""Friday"":{},""Monday"":{""0"":69,""1"":39,""10"":0,""1...",1,5.0,"{""1"":0,""2"":0,""3"":0,""4"":0,""5"":1}",-2.134072,115.452693,5436099151382005493,0x2dfab100168ad60f:0x4b70e76061ed46f5,ChIJD9aKFgCx-i0R9UbtYWDncEs,"[{""title"":""All"",""image"":""https://lh3.googleuse...","{""link"":"""",""source"":""""}"

In [19]:
kategori_dihapus = ['Night club', 'Car wash', 'Clothing store', 'Karaoke bar', 'Health consultant', 'Bar']

# Simpan baris yang kategorinya BUKAN bagian dari daftar di atas
df = df[~df['category'].isin(kategori_dihapus)]
df.info()

<class 'pandas.DataFrame'>
Index: 1237 entries, 0 to 1251
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   input_id            1237 non-null   str
 1   link                1237 non-null   str
 2   title               1237 non-null   str
 3   category            1237 non-null   str
 4   address             1237 non-null   str
 5   open_hours          1237 non-null   str
 6   popular_times       1237 non-null   str
 7   review_count        1237 non-null   int64
 8   review_rating       1237 non-null   float64
 9   reviews_per_rating  1237 non-null   str
 10  latitude            1237 non-null   float64
 11  longitude           1237 non-null   float64
 12  cid                 1237 non-null   uint64
 13  data_id             1237 non-null   str
 14  place_id            1237 non-null   str
 15  images              1237 non-null   str
 16  menu                1237 non-null   str
dtypes: float64(3), int64(1), str(12), uint64(1)
memory usage: 174.0 KB

In [20]:
# Simpan DataFrame ke file CSV
# index=False digunakan agar nomor baris pandas tidak ikut tersimpan sebagai kolom baru
df.to_csv('clean_data_cafekalsel.csv', index=False, encoding='utf-8')