Import Library

In [1]:
import pandas as pd
import re
import seaborn as sns
import matplotlib.pyplot as plt

Import dataset & cleaning

In [3]:
df = pd.read_csv("anies.csv")
df.head(2)

,Unnamed: 0,created_at,id_str,full_text,quote_count,reply_count,retweet_count,favorite_count,lang,user_id_str,conversation_id_str,username,tweet_url
0,0,Fri Dec 15 04:04:44 +0000 2023,1.735511e+18,"@dedy_pram Pastilah, Prabowo Anies nggak punya...",0.0,0,0.0,0.0,in,797761417894051840,1.735147e+18,MarahIchsan,https://twitter.com/MarahIchsan/status/1735511...
1,1,Fri Dec 15 04:04:33 +0000 2023,1.735511e+18,Suasana pedesaan memang selalu menyenangkan......,0.0,0,0.0,0.0,in,936445409605459968,1.735511e+18,Agung_wiyo,https://twitter.com/Agung_wiyo/status/17355111...

In [4]:
df = df[['full_text', 'username', 'created_at']]
df

,full_text,username,created_at
0,"@dedy_pram Pastilah, Prabowo Anies nggak punya...",MarahIchsan,Fri Dec 15 04:04:44 +0000 2023
1,Suasana pedesaan memang selalu menyenangkan......,Agung_wiyo,Fri Dec 15 04:04:33 +0000 2023
2,Program anies hanyalah mengubah nama rumah sak...,Alfakton_i,Fri Dec 15 04:04:31 +0000 2023
3,@kumparan @aniesbaswedan anies... BERBOHONG DA...,justtheway333,Fri Dec 15 04:04:27 +0000 2023
4,Tidak Bicara Sesuai Fakta! Anies Dengan Lantan...,singgihabdrchmn,Fri Dec 15 04:04:26 +0000 2023
...,...,...,...
510,Tiga untuk Indonesia lebih baik . tag || Gac...,TugimanPresiden,Fri Dec 15 03:36:13 +0000 2023
511,@herculep638 Makanya susah memahami apa yg dis...,Pribumituan,Fri Dec 15 03:36:13 +0000 2023
512,"Buat Pak Anies ,bukankah anda saat itu yg KD G...",Kacaback678910,Fri Dec 15 03:36:12 +0000 2023
513,"Anies Baswedan, sosok pemimpin yang memahami b...",YKasmono4,Fri Dec 15 03:36:12 +0000 2023
514,Anies Baswedan diharapkan dapat membawa peruba...,DediSudraj83464,Fri Dec 15 03:36:12 +0000 2023

In [6]:
df.shape #ukuran data

(515, 3)

In [7]:
df = df.drop_duplicates(subset=['full_text'])

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df = df.dropna()  #menghapus variabel kosong

In [10]:
df.isnull().sum()

full_text     0
username      0
created_at    0
dtype: int64

In [11]:
def clean_twitter_text(text):
    text = re.sub(r'@[A-Za-z0-9_]+', '', text)
    text = re.sub(r'#\w+', '', text)
    text = re.sub(r'RT[\s]+', '', text)
    text = re.sub(r'https?://\S+', '', text)

    text = re.sub(r'[^A-Za-z0-9 ]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [12]:
df.shape

(508, 3)

In [13]:
df['full_text'] = df['full_text'].apply(clean_twitter_text)

In [14]:
df['full_text'] = df['full_text'].str.lower()

In [16]:
df

,full_text,username,created_at
0,pastilah prabowo anies nggak punya prestasi,MarahIchsan,Fri Dec 15 04:04:44 +0000 2023
1,suasana pedesaan memang selalu menyenangkan ud...,Agung_wiyo,Fri Dec 15 04:04:33 +0000 2023
2,program anies hanyalah mengubah nama rumah sak...,Alfakton_i,Fri Dec 15 04:04:31 +0000 2023
3,anies berbohong dan nipu tanpa rasa bersalah,justtheway333,Fri Dec 15 04:04:27 +0000 2023
4,tidak bicara sesuai fakta anies dengan lantang...,singgihabdrchmn,Fri Dec 15 04:04:26 +0000 2023
...,...,...,...
510,tiga untuk indonesia lebih baik tag gacoan dae...,TugimanPresiden,Fri Dec 15 03:36:13 +0000 2023
511,makanya susah memahami apa yg disampaikam anie...,Pribumituan,Fri Dec 15 03:36:13 +0000 2023
512,buat pak anies bukankah anda saat itu yg kd gu...,Kacaback678910,Fri Dec 15 03:36:12 +0000 2023
513,anies baswedan sosok pemimpin yang memahami ba...,YKasmono4,Fri Dec 15 03:36:12 +0000 2023
514,anies baswedan diharapkan dapat membawa peruba...,DediSudraj83464,Fri Dec 15 03:36:12 +0000 2023

Preprocessing

In [17]:
#Normalisasi

norm = {" yg ": " yang ",
        " ganjar " : " ",
        " prabowo " : " ",
        "nggak": "tidak",
        "gak" : "tidak",
        "bangetdari": "banget dari",
        "bgt" : "banget",
        "jd" : "jadi",
        "tuk" : "untuk",
        "kk" : "kakak"}

def normalisasi(str_text):
    for i in norm:
        str_text = str_text.replace(i, norm[i])
    return str_text

df['full_text'] = df['full_text'].apply(lambda x: normalisasi(x))
df

,full_text,username,created_at
0,pastilah anies tidak punya prestasi,MarahIchsan,Fri Dec 15 04:04:44 +0000 2023
1,suasana pedesaan memang selalu menyenangkan ud...,Agung_wiyo,Fri Dec 15 04:04:33 +0000 2023
2,program anies hanyalah mengubah nama rumah sak...,Alfakton_i,Fri Dec 15 04:04:31 +0000 2023
3,anies berbohong dan nipu tanpa rasa bersalah,justtheway333,Fri Dec 15 04:04:27 +0000 2023
4,tidak bicara sesuai fakta anies dengan lantang...,singgihabdrchmn,Fri Dec 15 04:04:26 +0000 2023
...,...,...,...
510,tiga ununtuk indonesia lebih baik tag gacoan d...,TugimanPresiden,Fri Dec 15 03:36:13 +0000 2023
511,makanya susah memahami apa yang disampaikam an...,Pribumituan,Fri Dec 15 03:36:13 +0000 2023
512,buat pak anies bukankah anda saat itu yang kd ...,Kacaback678910,Fri Dec 15 03:36:12 +0000 2023
513,anies baswedan sosok pemimpin yang memahami ba...,YKasmono4,Fri Dec 15 03:36:12 +0000 2023
514,anies baswedan diharapkan dapat membawa peruba...,DediSudraj83464,Fri Dec 15 03:36:12 +0000 2023

In [18]:
#Stopwords
import Sastrawi
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory, StopWordRemover, ArrayDictionary
more_stop_words = ["tidak"]   #buang kata yg gapunya bobot

stop_words = StopWordRemoverFactory().get_stop_words()
stop_words.extend(more_stop_words)

new_array = ArrayDictionary(stop_words)
stop_words_remover__new = StopWordRemover(new_array)

def stopword(str_text):  
    str_text = stop_words_remover__new.remove(str_text)
    return str_text

df['full_text'] = df['full_text'].apply(lambda x : stopword(x))
df.head()

,full_text,username,created_at
0,pastilah anies punya prestasi,MarahIchsan,Fri Dec 15 04:04:44 +0000 2023
1,suasana pedesaan memang selalu menyenangkan ud...,Agung_wiyo,Fri Dec 15 04:04:33 +0000 2023
2,program anies hanyalah mengubah nama rumah sak...,Alfakton_i,Fri Dec 15 04:04:31 +0000 2023
3,anies berbohong nipu rasa bersalah,justtheway333,Fri Dec 15 04:04:27 +0000 2023
4,bicara sesuai fakta anies lantang sebut lampun...,singgihabdrchmn,Fri Dec 15 04:04:26 +0000 2023

In [ ]:
#Tokenize

tokenized = df['full_text'].apply(lambda x:x.split())  #memisahkan kata-kata
tokenized

0                     [pastilah, anies, punya, prestasi]
1      [suasana, pedesaan, memang, selalu, menyenangk...
2      [program, anies, hanyalah, mengubah, nama, rum...
3               [anies, berbohong, nipu, rasa, bersalah]
4      [bicara, sesuai, fakta, anies, lantang, sebut,...
                             ...
510    [tiga, ununtuk, indonesia, lebih, baik, tag, g...
511    [makanya, susah, memahami, apa, disampaikam, a...
512    [buat, pak, anies, bukankah, saat, kd, gubernu...
513    [anies, baswedan, sosok, pemimpin, memahami, k...
514    [anies, baswedan, diharapkan, membawa, perubah...
Name: full_text, Length: 508, dtype: object

In [20]:
#Stemming
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

def stemming(text_cleaning):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
    do = []
    for w in text_cleaning:
        dt = stemmer.stem(w)
        do.append(dt)

    d_clean = []
    d_clean = " ".join(do)
    print(d_clean)
    return d_clean

tokenized = tokenized.apply(stemming)

tokenized.to_csv('AfterProcess/ProcessingAnies.csv', index=False)
data = pd.read_csv('AfterProcess/ProcessingAnies.csv', encoding='latin1')

pasti anies punya prestasi
suasana desa memang selalu senang udara segar rimbun tumbuh hijau sungai jernih penuh ikanikan kecil besar tarik angin dieng gaco adidas semalem bukan ordal anies
program anies hanya ubah nama rumah sakit se indonesia wkwk jungkook is coming olivia gaco daesang bangtan debut karina wonbin batter up 100m views
anies bohong nipu rasa salah
bicara sesuai fakta anies lantang sebut lampung punya alat pantau polusi udara gaco anies gempa daesang pagi batter up 100m views pilih baik
prabowo sindir anies baswedan apbd paling besar kok mas anies gagal pimpin jakarta gaco anies gempa daesang pagi batter up 100m views pilih baik
alesan jelas pak anies jelas jelas jelas nyamasih engga pahamdungu arti
wow mantap sekali ini arti bro anies jadi presiden ri
dulu ajar majas kelas 8 smpsaya paham apa bilang pak anies kalo ga paham mungkin kenyam kelas 8
kasi kiki padahal fakta memang si anies jago kata kata demi tarik simpati padahal implementasi jamin nol cth waktu jadi tri gubernur aja kerja nya standar banget
anak anies cakep bener anak capres muka ga tengil
partai dukung pak anies tdk tahan jadi oposisinasdem pkb tuh msh yang jabat tri imin msh jabat wakil ketua dprri nampaknya betah banget dgn kekuasaanmundur dong
lah juga dulu dukung lebih liberal anies hrs lebih anti jokowipdip sejak kasus ahok
asli rada hoream euy ceunah bebas dapat sugan teh geus balik deui jadi anies era nurcholis madjid memorial lecture
bicara sesuai fakta anies lantang sebut lampung punya alat pantau polusi udara gaco anies gempa daesang pagi batter up 100m views pilih baik
prabowo sindir anies baswedan apbd paling besar kok mas anies gagal pimpin jakarta gaco anies gempa daesang pagi batter up 100m views pilih baik
yang bilang anies modal kata doang pacar eco park tebet musuhin aja
sayang banyak msh dukung anies dateng mas baru di lampung kemaren berani banget ya juga kayak bilang takut sih kalo hadepan lgsg buat desak anies wkwk
anies pks
gerindra bantah soal anies bilang bisnis macet gegara jadi oposisi
anies ikut kubur harun tahun 2019 berita apakah kata hoax padahal beliau ikut kubur
anies baswedan jawab tanya debat bukti nyata kerja sangat muas
anies tuh cerdas utama soal janji transportasi jaklingko mau rekrut pak iganisus pilih sudah banyak tadi nya kurang bijak aja harus bawa ulama gimana kalo pendetapastorpemimpin agama juga timbang opini nya hanya cuman ulama
karakter wowo vs anies jauh lah bangmbok legowo ajaanies simpati publik luas sedang wowo sebaliknyasesederhana dipahaminyajgn kita jadi parasocial relationship disorder
kalau ga kerja bidang nya jago nyindir orang anies
paragraf satu udah dijelasin sama pa anies sendiri tonton geh video biar paham konteks ape2 ditelen mentah2 paragraf dua nama pamrih kata paling ikhlas ko ungkit ko nyapres paragraf tiga etika kata bro awokwokwok mending ngaca dulu dah
bicara sesuai fakta anies lantang sebut lampung punya alat pantau polusi udara gaco anies gempa daesang pagi batter up 100m views pilih baik
prabowo sindir anies baswedan apbd paling besar kok mas anies gagal pimpin jakarta gaco anies gempa daesang pagi batter up 100m views pilih baik
itu anak anies emang cantik banget senyum
anies selalu komitmen ununtuk wujud ubah positif baik masyarakat negara
menang anies gub dki klaim penuh gerindra baik dukung modal logistik sungguh sombong hilang jasa2 partai2 relawan2 dan rakyat dki pilgub dki lebih jasa
lama masa jabat gubernur anies pimpin bagai proyekpembangunan ununtuk sejahtera rakyat
anies baswedan ajak warga ununtuk menunjukakakan kuat bangsa semangat juang
pikir anies debat perdana sedikit mampu cipta ubah positif masyarakat
anies angkat alis adad pernah ada guna fakedeep aidasar buzzer polri suka buat fitnah
2019 anies jadi gubernur ikut pilpres krn 2024 anies calon nasdem apa salah nasdem jeli krn negara butuh sosok anies rakyat ubah ununtuk adil sosial seluruh rakyat indonesia
bagai inisiatif kembang jakarta anies jadi contoh nyata banyak orang
ordal anies profesional integritas
anies baswedan muhaimin iskandar dong ununtuk indonesia lebih baik
debat banyak buah pikir anies pada akhir memang benarbenar manfaat ununtuk cerdas warga negara
udah rahasia umum lah ga usah tutup bagaimana anies nikmat politik identitas dia betulbetul ambil untung
anies baswedan tuding capres banyak janji timnas amin janji ukur
org cerdas paham apa sampai pak anies klo otak cetek males mikir nilai njelimet
bicara sesuai fakta anies lantang sebut lampung punya alat pantau polusi udara gaco anies gempa daesang pagi batter up 100m views pilih baik
prabowo sindir anies baswedan apbd paling besar kok mas anies gagal pimpin jakarta gaco anies gempa daesang pagi batter up 100m views pilih baik
buzzerrp paslon no 2 habis akal amp narasi ununtuk serang anies makanya pakai methode fitnah receh
anies bangun jakarta lebih lanjut ramah lingkungandan pasti tumbuh kota beri manfaat seluruh warga
janji sdh tdk tunai tdk nyapres lama masa jabat gub dki kalau sdh selesai selesai janji mission accomplished smp kpn pak anies nyapres kl tiap priode kalah terus amp nyapres terus etika koyol tau
foodeatate gagal pesawat tempur rongsokanhutang kemenhan trilyunan benuntuk bengis 270 juta lebih rakyat indonesia saran tim tkn banyak cermin serang pak anies akhlak kalian pada benar
ga bang aman anies pernah tegor rijik suruh bayar denda kok waktu buat kerumun pas covid bukti
gw tidak bahas dki debat jujur gw udah lunak sama anies siap terima mungkin jadi presiden gw ngomong gitu baca ttg berita kontrak politik anyway di twit awal gw dki negara
iya kok disurvey kok unggul
buni yani kata potong video pidato ahok tim cybernya jadi ketimbang anies tak punya masa yang lebih bertanggungjawab yang gera kelompok brutal 212
la emang usung anies pkb nasdem oposisi
buzzer anies follower ribu klo tweet bayar
bicara sesuai fakta anies lantang sebut lampung punya alat pantau polusi udara gaco anies gempa daesang pagi batter up 100m views pilih baik
prabowo sindir anies baswedan apbd paling besar kok mas anies gagal pimpin jakarta gaco anies gempa daesang pagi batter up 100m views pilih baik
anies bagus sebenernya kunci sih ka belakang jg ga ngapa2in kalau aniesnya busuk baru bahaya kalau presiden skrg ga berani komen kasar khawatir knp2
layak jadi presiden pantesan pernah menang dulu dukung hanya 2 pilih sekarang anies paling layak semua
dulu sih 2 kali milih sekarang sih udah makin yakin pilih anies
anies baswedan tuding capres banyak janji timnas amin janji ukur
anies baswedan tuding capres banyak janji timnas amin janji ukur
wkwkwk dukung anies kek gin
waktu debat perdana pak anies menunjukakakan politis intelek setel jas peci
yg sampai kiky malah bagus kok justru puji anies
lihat debat anies selalu memilikikemampuan rancang terap solusisolusi kreatif
lama debat anies milik banyak solusi kena masalah timpang jadi indonesia
bicara sesuai fakta anies lantang sebut lampung punya alat pantau polusi udara gaco anies gempa daesang pagi batter up 100m views pilih baik
prabowo sindir anies baswedan apbd paling besar kok mas anies gagal pimpin jakarta gaco anies gempa daesang pagi batter up 100m views pilih baik
lama debat nya anies kenal programprogram ununtuk solusidari masalah ada dalam penididikan transportasi lingkung
seinget ku 212 yang datang makruf amin sama jokowi anies ga datang acara 212 monas
anies dominasi debat pertama retorika baik nilai anies punya leluasa serang gagas kandidat karena usung visi ubah
sama sama2 mantan napi korupsi jadi timses resmi nasional anies ga sih
lama debat langsung anies menunjukakakan gambar diri orang ajar
haiii bestie saat debat perdana caprescawapres kemaren malam sisa momen dramatis sang pangeran lupa kalau lagi ada area mimbar debat bukan tanding bola sang pangeran ngosngosan awokawokawok gaco anies semalem ordal
anies si dablek habis uang negara 80 triliun tak atas polusi jungkook is coming olivia gaco daesang bangtan debut karina wonbin batter up 100m views
ayo bli ketut maen2 lah jakarta biar rasa maju jakarta sejak pimpin anies
lama debat anies tampil tenang jelas segala tanya atas masalah bahas debat
kasih fakta nih
iya saya jadi malu cari presiden lo bukan ketua rt
debat anies hendak manfaat tren populer sosial media ununtuk menyebarluaskan kritik utama kritik merdeka dapat
pak anies janji warga jakarta u jalan amanah smpai tuntas pimpin ibu kota jakarta apakh salah bang kl skrg pak anies niat bawa ubah apakh juga salah tdk etika bangrekam jejak sdh bukti beliau tuntas amanah pimpin jkt
anies orang pimpin milik semangat luar biasa kenal solusi ununtuk hadap bagai tantang
anies milik mampu eksekusi implementasi bijak laku sungguhsungguh ununtuk capai hasil harap
anies contoh nyata orang pimpin milik semangat tak goyah
analisa mu kalau jujur bkn benar benar pintar menganalisa tp si buah hati jadi sesuai hati nuranisebenarnya pa wowo sdh emosi tp ununtuk tahan emosi nya ucap lah mas aniesmas anies
nilai anies hasil jelas masalah muncul dalam debat konkret
rekomendasi buku anak ununtuk anak usia 17 tahun buku full gambarwarna buat koleksi tag besok senin selasa rabu kamis jumatberkah sabtu malam minggu malmingan pagiii sarap makan siang gaco anies surabaya gempa olivia hari ibu dana ginting desember
anies sosok milik tekad luar biasa hadap rintang menghadangnya
anies selalu menunjukakakan teguh tekad luar biasa cari solusi ununtuk wujud visi misi maju daerah
pakar komunikasi politik universitas brawijaya verdi firmantoro nilai anies capres runut sampai materi debat
dengankomitmennya baik bangun anies cipta landas ununtuk masa depan lebih baik
takut banget da anies jadi presiden yang darah sumbar malu sama kengototan bela prabowo
waktu uas sadar kita pilih sandal jepit bakiak sama buruk harus tetap pilih sekarang anies yang lebih punya ide gagas sandal jepit tinggal
lihat debat nilau anies pimpin selalu milik solusi hadap bagai rintang
sangat lihat debat capres 2024 anies baswedan capres bisa jawab tanya jawab muas
gabisa cari salah anies sampe salah dukung cari mo milih presiden mo milih dukung
semua omong anies ngibul program program amburadul jungkook is coming olivia gaco daesang bangtan debut karina wonbin batter up 100m views
debat capres anies baswedan tanggap nyata argumen sangat bobot tentu muas rakyat
klo ulama2 tahu jejak digital pak anies waktu wawancara dgn najwa shihabselama pak nyapres tdk maju nyapresternyata waktu debat pojok pak mosok sih orang ingkar janji gitu dukung tak iye
hanya dapat anggota dpr dr psi jadi pegang yah wakakaka kamu tnton video fullnya youtube justru anies jegal anggar makanya tonton youtube selesai
anies jago debat jago ngeles kalau tanya jawabanya mutar2 spy ngeles kata yang kerja bajing bohong etika yang usung jadi gubernur mata najwa janji calon diri jk juga mecalonkan diri
ahok produk masuk anies
anies the legend of avathar sang kendali angin
iyaaasambil jilatin lubang pantatadmin socmed emang otak sengklek
kalo balik tanya pak bagaimana tanggap hadap anies jawab sorry ni ye asumsi awokwokwok
anies baswedan sebut tak tahan jadi oposisi perintah nyata lontar debat perdana capres ban partai gerindra
anies sindir tak tahan jadi oposisi nusron wahid rekonsiliasi nasional
resmi dukung uas hrs pakta integritas harus laksana anies baswedan
hari debat capres no urut 1 anies baswedan unjung ustadz abdul somad riau adapun capres nomor urut 2 subianto nyanyi joget sama alumni akmil presiden ri 6 susilo bambang yudhoyono
antara anies ama wowo emang sama sama bego apa gimana tolak lupa
serang balik anies strike
abraham samad gugat pilih jadi presiden kelleher olivia anies adidas daesang gaco surabaya pagi gempa ginting dana brighton moldova molly pilih baik first lady
biasaaa buzzer mahh kalo nemu lemah anies akhir bikin2 hasut kalo engga tidak makan
ibarat tanding sepak bola suporter kalah kecewangomel bahagia cari cari salah musuh yang alami kubu hanya dukung team anies yng bahagia ini
genuinely nanya misal aku pilih aniesmuhaimin tp aku ga pilih legislatif pks nasdem nya contoh pks ruu nya problematik gitu gimana
jelas tak level laaah mbak pak anies tuuuh capres bang fahri cuman juru bicara kl buat tweet tuuuh pak baru tuuuh level dgn pak aniessama2 capres cerdas dikit berhusnudzon napa siih mbak kata nya pilpres hrs gembiralupa yaa gemoy
anies angkuh menetidakan hukum padahal para dukung masalah berani tego gaco olivia jill biden daesang gempa adidas surabaya batter up 100m views pilih baik melania bangtan debut
mmmmkayaknya ngga yakin nih sama kualitas capres dukung butuh bawa2 nama orang delusi anda lebih baik anies wake up bro ikhlas hati ununtuk baik indonesia seluruh biar baik yang pilih
anies sosok capres tidak milik adab orang lebih tua gaco olivia jill biden daesang gempa adidas surabaya batter up 100m views pilih baik melania bangtan debut
macam serang anies lalu anies nampol balik woiii
jadi anggota mrk yang bunuh kan 6 orang udah bunuh ga dapet jabat anies ga nolong klo mrk mau nyoblos dukung cm hak warga negara mau golput jg hak mrk lama mrk bukan genocide supporters or genocide actors tidak kasih jabat mrk ga bsa buat ap2
anies selalu jebak asumsi pribadi ada dukung bukti fakta gaco olivia jill biden daesang gempa adidas surabaya batter up 100m views pilih baik melania bangtan debut
ga yang peduli org2 km50 puja riziq soal ga usah turun suara anies dgn org2 kaya riziq ikut
jgn suuzon bang orang paling ikhlas pak mungkin main cara2 kotor itu pak ikhlas kalo tidak pilih pak ikhlas klo anies yang pilih tapi kok aku percaya 99 sama statemt abang
sukasuka orang lah mau milih anies kaga lucu banget dukung anies untukang guilttrip orang liat noh swing voters belum mau ngevote anies awokwok
anies lihat munafik kait sikap lanjut ikn gaco olivia jill biden daesang gempa adidas surabaya batter up 100m views pilih baik melania bangtan debut
anies sama jadi seolah2 kerja sama padahal ngalir aja
moga anies menang amin aamiin amin gaes
agama islam ajar ununtuk bakti dua orang tua dinding adidas karina surabaya anies daesang gempa islam
akhir anies kena batu ucap kait udara ber ktp gaco olivia jill biden daesang gempa adidas surabaya batter up 100m views pilih baik melania bangtan debut
celana panjang chino pria murah kualitas dapat cashback 40 shopee video anies gaco daesang surabaya gempa ayo lihat video shopee video
jelas lebih pantes anies
serang yang kerja si memed hari buzzer ayah semua medsos debat kpu serang kalap sekali rl nyata ada hasil cenderung negatif anies pelan2 banyak bicara semua kalangantitik cerah
panggung debat panggung ny sm anies klo kalah panggung langsung ulti nya pake surat lah lah lah nyari kunci pokok hahahahaaa badut politik
tinggal dukung anies baswedan lebih mampu ayom rakyat indonesia depan
singgung soal janji tak maju ada pilpres anies komitmen dki
anies memang bisa percaya kata2 nya untukang obral janji
parah banget cantik udah gitu keren dukung pak anies sempurna
haha janji apa batas hak orang ununtuk abdi negara emang jamin hak hidup anies baswedan sedih sekali kualitas pikir makin turun
fans bole otak pakai nyata jadi hoax hoax kalian buat jadi nyata nonton bnyk
main aman gimana jauh pikir awam gw jelas banget kok sikap anies ttg ikn apa lo doang ga faham
ayoviralkan rekam jejak anies rasyid baswedan pimpin dki jkt
nama gerinda jg naik pdhl lebih dr 10th lalu pasang dgn mega seolaholah gerindra lebih kecil dr anies njirrtt
betulcocok jadi bapak bangsa king maker tp cocok jadi presidenpresiden biar cocok2 ajaanies ganjar
hatihatianies dekat abdsomad
anies cerdas amp jujur fakta
pada takut sama fpi dah organisasi udah bubar kok takut sama ideologi emang power besar apa pas anies jabat jadi gub dki ngadain christmas carol gitu mantan pentol fpi rusuh aduh
ampun ama ni orang benci fpi hrs gerombol nya kena anies dulu kena tuduh mobilisasi 212 keluarga cikeas eh pangeran cikeas kalah putar pertama kena anies
lama tuan timbul hidup anies gausah nyapres gitu etika tidak bicara2 soal etika kaya tuan plongo lebih fahan sdh menang 2x tuan timbul
prabowo kait apbd dki puluh trilyun dgn mampu anies atas polusi padahal masalah polusi jkt bukan soal duit tentang wenang perintah pusat stupid soal lingkung yang harus koreksi
anies lbh baik banding kamu hya dewan jilat amp munafik
hukum tetidak ununtuk semua capres anies singgung gibran papar visi misi soal penetidakan hukum
lamongan viva jatim naskah uji kelas xi smk muhammadiyah sekar kabupaten lamongan pampang foto calon presiden capres anis baswedan naskah uji mata ajar bahasa inggris dapat foto anies baswedan sebut dapat poin b nomer 21 23
ini 13 poin pakta integritas pakat paslon 1 anies baswedan muhaimin iskandar dapat dukung ijtima ulama sepenuh
saha ieu teh meuni geulis kitu sampai salam si cantik dan kasih tahu bahwasanya akan pilih pak anies ununtuk jadi presiden ri
desak anies desak nya bukan asal nama biar tarik acara orang beneran ngedesak keras depan muka pak anies
kasi mau pilih anies dibully emak
kutip anies dasar atas berita 2019 prioritas ununtuk bangun pedestrian ununtuk cak imin beliau bicara ketidaksepakatannya atas pindah ibukota justru teguh stereotipe kalimantan
2 hari lalu anies tetap trending twitterx tanya
gilir mas anies ngegas
anies musuh negara wakanda harap rakyat indonesia wakanda no more indonesia forever
anies ga tolak memang gera krn jokowi literally ga yang berani larang krn memang massa sedang gusar jelas anies bukan inisiator dalang ga nge encourage ga libat jadi sama sekali
pak pernah usung anies tpi ungkit d debat terus bakas pak anies salah ingat gerindra terima banyak manfaat saaat dukung anies
pak anies tugas nya pak surya lantas tak level tuh jongos nya yaaa mbak
prabowo nilai sangat santai sangat tenang tak lihat gugup sama sekali bahkan beberapa kali justru hasil cair suasana jokesnya gaya silat gemoy pasca jawab tanya anies lalu ikut riuh tawa tonton pimpin tegas
begini mentah dam sifat capres anies sombong angkuh
anies menang pilkada habib rizieq ga minta apa gajadi apa
anies baswedan tuding capres banyak janji timnas amin janji ukur
mereka2 alergi fpi jakarta jadi neraka jaman pak anies shummum bukmun umyun fa hum l yarjin
anies baswedan cerita ustad abdul somad heran ada doa debat capres
temen ngoceh soal debat pilpres gw jadi dengar baik aja dech y bagus kata pak anies tp d harap guna data spya gen z kosong jadi faham visi misi pak anies
nasdem aju ganjaranies nasdem ini pasang rekonsiliasi bangsa negara pascaketerbelahan milu 2019 bukan versi fahri hamzah ngarang pak lurah neng ae bulan tunggu tak respons malah ab hendak kriminalisasi
harus mas anies briefing dulu ngomong isu demokrasi kait oposisi partai usung utama nasdem pkb ibarat dulang air ciprat muka sendiri
pantesan kalo polling x anies menang mulucocok jadi presiden medsos doangnegeri maya
bang andre etika angkuh klaim anies jadi gub dki gerindra dengan tapi jasa jasa partai relawan2 rakyat dki yakin kalau dan gerindra sendiri ngusung anies tidak akan jadi
anies tunjuk ada penetidakan hukum mata orang tua korban cari adil saat ini
mustahil bro nu pkb mau dikemanain anies masa jabat semua agama tara fpi diem ga aneh beras bansos jadi bancak anak buah pak heru aja cium kalo anies kasih dana lebih fpi tahu viral lah
koq kamu sesal nyata anies nus laku nya lah ga tahan tolol
kyk anies udah ngegolin tp anulir offset
2x periksa kpk anies datang 2x tidak bukti
bayang kalau tiba2 orang banyak pilih anies lalu menang pas menang baru tau kelompok sama ormas2 tsb apa rasa mereka2 tipu 2 kali tsb
berani terobos area penetidakan hukum paling rawan debat capres reza indragiri siapa kapolri anies
wkwkw iya kemarin2 kan efpei 212 dr beritane condong apalagi beberapa tokoh intine spt babe haekal neno warisman fahri hamzah eh gilir tokoh2 lain anies baswedan lsg cap politik identitas
mana hebat wowo gertak si owe ciut dah gk aneh wajah perisai nya awokwoox

Translate

In [2]:
import pandas as pd
data = pd.read_csv('AfterProcess/ProcessingAnies.csv', encoding='latin1')
data.head()

                                           full_text
0                         pasti anies punya prestasi
1  suasana desa memang selalu senang udara segar ...
2  program anies hanya ubah nama rumah sakit se i...
3                       anies bohong nipu rasa salah
4  bicara sesuai fakta anies lantang sebut lampun...

In [ ]:
from translate import Translator

def convert_eng(tweet):
    translator = Translator(to_lang='en', from_lang='id')
    translation = translator.translate(tweet)
    return translation

data['tweet_english'] = data['full_text'].apply(convert_eng)  
data.to_csv('AfterProcess/TranslateAnies.csv')

In [6]:
data = pd.read_csv('AfterProcess/TerjemahanAnies.csv', index_col=0)
data

,full_text,tweet_english
0,pasti anies punya prestasi,surely prabowo anies has achievements
1,main aman gimana jauh pikir awam saya jelas ba...,playing it safe how far do you think the publi...
2,ayoviralkan rekam jejak anies rasyid baswedan ...,ayoviralkan track record anies rasyid baswedan...
3,suasana desa memang selalu senang udara segar ...,village atmosphere is always happy lush fresh ...
4,program anies hanya ubah nama rumah sakit se i...,anies program only change the name of the hosp...
...,...,...
273,singgung soal janji tak maju ada pilpres anies...,alludes to the promise of no progress there is...
274,anies memang bisa percaya kata2 nya tukang obr...,anies can indeed believe the words of the pled...
275,parah banget cantik udah gitu keren dukung pak...,"it's so beautiful, it's so cool to support Mr...."
276,haha janji apa batas hak orang untuk abdi nega...,haha promise what is the limit of people's rig...
277,fans bole otak pakai nyata jadi hoax hoax kali...,fans bole brains use real so your hoax hoax ma...

In [1]:
import preprocessor as p
from textblob import TextBlob
import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [6]:
import pandas as pd
data = pd.read_csv('AfterProcess/TerjemahanAnies.csv', index_col=0)
data_tweet = list(data['tweet_english'])
polaritas = 0

status = []
total_positif = total_negatif = total_netral = total = 0

for i, tweet in enumerate(data_tweet):
    analysis = TextBlob(tweet)
    polaritas += analysis.polarity

    if analysis.sentiment.polarity > 0.0:
        total_positif += 1
        status.append('Positif')
    elif analysis.sentiment.polarity == 0.0:
        total_netral += 1
        status.append('Netral')
    else:
        total_negatif += 1
        status.append('Negatif')

    total += 1

print(f'Hasil Analisis Data:\nPositif = {total_positif}\nNetral = {total_netral}\nNegatif = {total_negatif}')
print(f'\nTotal Data : {total}')

Hasil Analisis Data:
Positif = 138
Netral = 83
Negatif = 57

Total Data : 278

In [ ]:
data['klasifikasi'] = status
data